spring:
  cloud:
    config:
      name: application-zuul
      profile: dev
      #uri: http://localhost:8848
      discovery:
        service-id: CONFIG-SERVER
        enabled: true #单机配置
  application:
    name: GATEWAY-ZUUL
eureka:
  instance:
    prefer-ip-address: true #以ip注册到erueka中而不是主机名
  client:
    serviceUrl:
      defaultZone: http://root:880811@localhost:8761/eureka/ #eureka的注册地址876

