spring:
  cloud:
    config:
      name: application-system
      profile: dev
      discovery:
        service-id: CONFIG-SERVER #配置中心集群配置
        enabled: true

eureka:
  instance:
    prefer-ip-address: true #以ip注册到erueka中而不是主机名
  client:
    serviceUrl:
      defaultZone: http://root:880811@localhost:8761/eureka/ #eureka的注