server:
  port: 8848

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ClownWong/hrm-config.git
  application:
    name: CONFIG-SERVER

eureka:
  instance:
    prefer-ip-address: true #以ip注册到erueka中而不是主机名
  client:
    serviceUrl:
      defaultZone: http://root:880811@localhost:8761/eureka/ #eureka的注册地址876
